{% set version = "1.1.0" %}

package:
  name: symuflow
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
  host:
    - boost-cpp
    - libgdal=3.2.1
    - xerces-c=3.2.3
    - xqilla=2.3.4
    - rapidjson
    - unixodbc
    - symucore
    - python=3.9
  run:
    - boost-cpp
    - libgdal=3.2.1
    - xerces-c=3.2.3
    - xqilla=2.3.4
    - rapidjson
    - unixodbc
    - symucore
    - python=3.9

about:
  home: https://github.com/licit-lab/symuflow
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Flow engine for traffic simulation.
  dev_url: https://github.com/licit-lab/symuflow
